// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR91nbACm5GbEW2bWKiq0i6_qRLh48dyY',
    appId: '1:524718286486:web:10ccb553441e1e9b2fc4b7',
    messagingSenderId: '524718286486',
    projectId: 'bengkels',
    authDomain: 'bengkels.firebaseapp.com',
    storageBucket: 'bengkels.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMWcRrPbiLCUDLbjwCrdvTT-JC-DeuOLw',
    appId: '1:524718286486:android:993685e71d1d33db2fc4b7',
    messagingSenderId: '524718286486',
    projectId: 'bengkels',
    storageBucket: 'bengkels.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkkQokpK4KyUJvrdPyhSwZ0w2990YPBQ',
    appId: '1:524718286486:ios:75c8f7af7d9475922fc4b7',
    messagingSenderId: '524718286486',
    projectId: 'bengkels',
    storageBucket: 'bengkels.firebasestorage.app',
    iosBundleId: 'com.example.bengkelPakistunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRkkQokpK4KyUJvrdPyhSwZ0w2990YPBQ',
    appId: '1:524718286486:ios:75c8f7af7d9475922fc4b7',
    messagingSenderId: '524718286486',
    projectId: 'bengkels',
    storageBucket: 'bengkels.firebasestorage.app',
    iosBundleId: 'com.example.bengkelPakistunes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR91nbACm5GbEW2bWKiq0i6_qRLh48dyY',
    appId: '1:524718286486:web:a28df6480cc623812fc4b7',
    messagingSenderId: '524718286486',
    projectId: 'bengkels',
    authDomain: 'bengkels.firebaseapp.com',
    storageBucket: 'bengkels.firebasestorage.app',
  );
}
